import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
import { Suspense } from "react";
import PublicLayout from "@/components/PublicLayout";
import { Toaster } from "react-hot-toast";
import { Toaster as Sonner } from "sonner";
import localFont from "next/font/local";

const kaitiFont = localFont({ src: "../fonts/KaiTi.ttf" });

export const metadata: Metadata = {
  title: {
    default: "Bhuddist form",
    template: "%s | Bhuddist form",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kaitiFont.className} suppressHydrationWarning={true}>
        <Toaster
          position="top-right"
          containerClassName="!z-[99999999] !top-32 !right-10"
        />
        <Sonner />
        <ToastContainer />
        <Suspense>
          <PublicLayout>{children}</PublicLayout>
        </Suspense>
      </body>
    </html>
  );
}
